version: '3.8'

services:
  db:
    container_name: "${NETWORK_CODE}_db"
    image: postgres:13
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres

  core:
    container_name: "${NETWORK_CODE}_core"
    image: abxit/kinesis-core:v18.5.0-kinesis.1
    restart: on-failure
    depends_on:
      - db
    ports:
      - 11625
      - 11626
    entrypoint: 
    - bash
    - -c
    - |-
      /scripts/core-init.sh
      sleep infinity
    volumes:
      - $PWD/config:/config
      - $PWD/scripts:/scripts
    environment:
      - NETWORK_CODE=${NETWORK_CODE}
      - >-
        DATABASE_URL=postgresql://dbname=${NETWORK_CODE}-core host=${NETWORK_CODE}_db user=postgres password=postgres

  horizon:
    container_name: "${NETWORK_CODE}_horizon"
    image: abxit/kinesis-horizon:v2.16.1-kinesis.4
    restart: on-failure
    depends_on:
      - db
    ports:
      - $HORIZON_HTTP_PORT:8000
    environment:
      - NETWORK_PASSPHRASE=${NETWORK_PASSPHRASE}
      - >-
        DATABASE_URL=postgresql://postgres:postgres@${NETWORK_CODE}_db:5432/${NETWORK_CODE}-horizon?sslmode=disable
      - >-
        STELLAR_CORE_DATABASE_URL=postgresql://postgres:postgres@${NETWORK_CODE}_db/${NETWORK_CODE}-core?sslmode=disable
      - STELLAR_CORE_URL=http://${NETWORK_CODE}_core:11626  # pointing to your local stellar-core service above
      - INGEST=true
      - ENABLE_CAPTIVE_CORE_INGESTION=false
      - INGEST_FAILED_TRANSACTIONS=true
      - HISTORY_ARCHIVE_URLS=https://${NETWORK_CODE}-arch-syd-node2.kinesisgroup.io
      - PER_HOUR_RATE_LIMIT=200000
    entrypoint:
    - bash
    - -c
    - |-
      sleep infinity
    volumes:
      - $PWD/scripts:/scripts

# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.2.0/24
